
export const ongoingProjects = [
  {
    title: '33 KV Distribution Line - NESCO, PBS, BREB, WZPDCL',
    description: 'Design, supply, installation, and commissioning of 33 KV distribution lines for multiple power sector companies across Bangladesh.',
    imageSrc: '/uploads/projects/33kv-distribution-line.jpg', // Will be replaced with actual image
    imageHint: 'distribution line installation',
    href: '/projects/ongoing/33kv-distribution-line',
    category: 'Distribution Lines',
    client: 'NESCO, PBS, BREB, WZPDCL',
    year: '2024',
    status: 'In Progress',
    features: [
      'Complete pole installation and line setup',
      'Advanced safety protocols during installation',
      'Multiple connection points across service areas',
      'Heavy equipment operation for pole placement'
    ],
    location: 'Multiple districts in Bangladesh'
  },
  {
    title: '132KV, 230KV, 400KV Transmission Line - PGCB',
    description: 'High-voltage transmission line project spanning multiple districts including Bogura, Chittagong, Cumilla, Fani, and Tangile.',
    imageSrc: '/uploads/projects/transmission-line-pgcb.jpg', // Will be replaced with actual image
    imageHint: 'high voltage transmission line',
    href: '/projects/ongoing/transmission-line-pgcb',
    category: 'Transmission Line',
    client: 'PGCB',
    year: '2024',
    status: 'In Progress',
    features: [
      'High-voltage power transmission infrastructure',
      'Multi-district coverage across Bangladesh',
      'Advanced engineering for stability and safety',
      'Integration with national power grid'
    ],
    location: 'Bogura, Chittagong, Cumilla, Fani, Tangile'
  },
  {
    title: 'Palmal Group Factory - 610 KW Solar Plant',
    description: 'Large-scale rooftop solar power installation for Palmal Group Factory in Gazipur Borobari, providing sustainable energy solutions.',
    imageSrc: '/uploads/projects/palmal-solar-plant.jpg', // Will be replaced with actual image
    imageHint: 'rooftop solar installation',
    href: '/projects/ongoing/palmal-solar',
    category: 'Solar Plant',
    client: 'Palmal Group',
    year: '2024',
    status: 'In Progress',
    features: [
      '610 KW capacity solar power generation',
      'Rooftop installation maximizing space efficiency',
      'Reduced carbon footprint for industrial operations',
      'Custom design for factory energy requirements'
    ],
    location: 'Gazipur Borobari'
  },
  {
    title: '1 MWP Solar System at Bhan Char Upazila',
    description: 'Large-scale solar power plant installation in Hatiya, Noakhali district under Chittagong Division, providing sustainable energy to the region.',
    imageSrc: '/uploads/projects/bhan-char-solar.jpg', // Will be replaced with actual image
    imageHint: 'solar power plant',
    href: '/projects/ongoing/bhan-char-solar',
    category: 'Solar Plant',
    client: 'Government of Bangladesh',
    year: '2024',
    status: 'In Progress',
    features: [
      '1 MWP capacity solar power generation',
      'Ground-mounted solar array installation',
      'Power supply for remote area development',
      'Climate-resilient energy infrastructure'
    ],
    location: 'Bhan Char Upazila, Hatiya, Noakhali'
  },
  {
    title: '33/11 KV GIS Substation - DESCO, NESCO, WZPDCL',
    description: 'Design, supply, installation, testing and commissioning of 33/11 KV Gas Insulated Substations for multiple power distribution companies.',
    imageSrc: '/uploads/projects/gis-substation.jpg', // Will be replaced with actual image
    imageHint: 'gas insulated substation',
    href: '/projects/ongoing/gis-substation',
    category: 'Substation',
    client: 'DESCO, NESCO, WZPDCL, Adamjee EPZ, CEPZ',
    year: '2024',
    status: 'In Progress',
    features: [
      'Advanced GIS technology implementation',
      'Compact design for space optimization',
      'Enhanced safety and reliability features',
      'Integrated control and monitoring systems'
    ],
    location: 'Multiple locations including Adamjee EPZ, CEPZ'
  },
  {
    title: '132 KV AIS Substation - PGCB, Chittagong',
    description: 'Air Insulated Substation project for PGCB at Chittagong RSRM Factory, enhancing power distribution capabilities in the industrial zone.',
    imageSrc: '/uploads/projects/ais-substation-chittagong.jpg', // Will be replaced with actual image
    imageHint: 'air insulated substation',
    href: '/projects/ongoing/ais-substation-chittagong',
    category: 'Substation',
    client: 'PGCB',
    year: '2024',
    status: 'In Progress',
    features: [
      '132 KV capacity power distribution',
      'Industrial-grade equipment installation',
      'Custom design for factory power requirements',
      'Integration with existing power infrastructure'
    ],
    location: 'Chittagong RSRM Factory'
  },
  {
    title: '132 KV GIS Substation - Chittagong RSRM Factory',
    description: 'Gas Insulated Substation installation at RSRM Factory in Chittagong, providing reliable power distribution for industrial operations.',
    imageSrc: '/uploads/projects/gis-substation-rsrm.jpg', // Will be replaced with actual image
    imageHint: 'gas insulated substation industrial',
    href: '/projects/ongoing/gis-substation-rsrm',
    category: 'Substation',
    client: 'RSRM Factory',
    year: '2024',
    status: 'In Progress',
    features: [
      'State-of-the-art GIS technology',
      'Industrial power distribution optimization',
      'Reduced maintenance requirements',
      'Enhanced safety features for industrial environment'
    ],
    location: 'Chittagong RSRM Factory'
  },
];

export const completedProjects = [
  {
    title: 'Palmal Group Factory - 610 KW Solar Plant',
    description: 'Successful installation of 610 KW rooftop solar power system for Palmal Group Factory in Gazipur Borobari, providing sustainable energy solutions.',
    imageSrc: '/uploads/projects/palmal-solar-plant.jpg', // Will be replaced with actual image
    imageHint: 'rooftop solar installation completed',
    href: '/projects/completed/palmal-solar',
    category: 'Solar Plant',
    client: 'Palmal Group',
    year: '2022',
    status: 'Completed',
    features: [
      '610 KW capacity solar power generation',
      'Rooftop installation maximizing space efficiency',
      'Reduced carbon footprint for industrial operations',
      'Custom design for factory energy requirements'
    ],
    location: 'Gazipur Borobari',
    testimonial: 'CEM Engineering delivered an exceptional solar power solution that has significantly reduced our energy costs and environmental impact.'
  },
  {
    title: '1 MWP Solar System at Bhan Char Upazila',
    description: 'Completed large-scale solar power plant installation in Hatiya, Noakhali district under Chittagong Division, providing sustainable energy to the region.',
    imageSrc: '/uploads/projects/bhan-char-solar.jpg', // Will be replaced with actual image
    imageHint: 'solar power plant completed',
    href: '/projects/completed/bhan-char-solar',
    category: 'Solar Plant',
    client: 'Government of Bangladesh',
    year: '2021',
    status: 'Completed',
    features: [
      '1 MWP capacity solar power generation',
      'Ground-mounted solar array installation',
      'Power supply for remote area development',
      'Climate-resilient energy infrastructure'
    ],
    location: 'Bhan Char Upazila, Hatiya, Noakhali',
    testimonial: 'The solar installation by CEM Engineering has transformed power availability in this remote area, supporting critical infrastructure and community development.'
  },
  {
    title: '33/11 KV GIS Substation - DESCO, NESCO, WZPDCL',
    description: 'Successfully completed design, supply, installation, testing and commissioning of 33/11 KV Gas Insulated Substations for multiple power distribution companies.',
    imageSrc: '/uploads/projects/gis-substation.jpg', // Will be replaced with actual image
    imageHint: 'gas insulated substation completed',
    href: '/projects/completed/gis-substation',
    category: 'Substation',
    client: 'DESCO, NESCO, WZPDCL, Adamjee EPZ, CEPZ',
    year: '2022',
    status: 'Completed',
    features: [
      'Advanced GIS technology implementation',
      'Compact design for space optimization',
      'Enhanced safety and reliability features',
      'Integrated control and monitoring systems'
    ],
    location: 'Multiple locations including Adamjee EPZ, CEPZ',
    testimonial: 'The GIS substation installation has significantly improved our power distribution reliability and reduced maintenance requirements.'
  },
  {
    title: 'Grameenphone Technology Infrastructure',
    description: 'Complete electrical infrastructure and technology setup for Grameenphone facilities.',
    imageSrc: 'https://placehold.co/600x400/7c3aed/ffffff?text=Technology+Infrastructure',
    imageHint: 'technology infrastructure',
    href: '/projects/completed/grameenphone-tech',
    category: 'Infrastructure',
    client: 'Grameenphone ingen technology',
    year: '2019',
    status: 'Completed',
    features: [
      'Complete electrical infrastructure setup',
      'Technology integration and installation',
      'Power distribution system implementation',
      'Safety and reliability features'
    ],
    location: 'Multiple locations'
  },
  {
    title: '1 MWP SOLAR SYSTEM AT BHAN CHAR UPAZILA HATIYA',
    description: 'Large scale solar power plant installation in Noakhali district under Chittagong Division.',
    imageSrc: 'https://placehold.co/600x400/7c3aed/ffffff?text=1MW+Solar+Plant',
    imageHint: 'solar power plant',
    href: '/projects/completed/bhan-char-solar',
    category: 'Solar Plant',
    client: 'Rohim afzoj company limited',
    year: '2019',
    status: 'Completed'
  },
  {
    title: 'Technap Rohingya Camp',
    description: 'Electrical infrastructure and power distribution system for refugee camp facilities.',
    imageSrc: 'https://placehold.co/600x400/ea580c/ffffff?text=Camp+Infrastructure',
    imageHint: 'camp infrastructure',
    href: '/projects/completed/technap-rohingya',
    category: 'Infrastructure',
    client: 'Zamil',
    year: '2019',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV NEW AIS SUBSTATION, FORIDPUR, NAGORKANDHA-2',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection Testing and commissioning.',
    imageSrc: 'https://placehold.co/600x400/f59e0b/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/foridpur-nagorkandha',
    category: 'Substation',
    client: 'TS TRANSFORMER',
    year: '2019-2020',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV NEW AIS SUBSTATION, JOSSOR-5',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection Testing and commissioning.',
    imageSrc: 'https://placehold.co/600x400/1e40af/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/jossor-5',
    category: 'Substation',
    client: 'TS TRANSFORMER',
    year: '2019-2020',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV NEW AIS SUBSTATION-FORIDPUR-4',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection Testing and commissioning.',
    imageSrc: 'https://placehold.co/600x400/dc2626/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/foridpur-4',
    category: 'Substation',
    client: 'TS TRANSFORMER',
    year: '2019-2020',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV NEW AIS SUBSTATION, KHULNA, KHALISPUR',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection Testing and commissioning.',
    imageSrc: 'https://placehold.co/600x400/059669/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/khulna-khalispur',
    category: 'Substation',
    client: 'TS TRANSFORMER',
    year: '2019-2020',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV NEW AIS SUBSTATION, Dikbazar, Khulna',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection, Testing, and Commissioning.',
    imageSrc: 'https://placehold.co/600x400/7c3aed/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/dikbazar-khulna',
    category: 'Substation',
    client: 'TS Transformer',
    year: '2019-2020',
    status: 'Completed'
  },
  {
    title: 'GIS 33/11 KV Substation, Adomjee Bepza, Naraoungonj',
    description: 'Earthing Goods supply, Fabrication, Installation, Erection, Testing, and Commissioning.',
    imageSrc: 'https://placehold.co/600x400/ea580c/ffffff?text=GIS+Substation',
    imageHint: 'gis substation',
    href: '/projects/completed/adomjee-bepza',
    category: 'Substation',
    client: 'Multi Trade Enterprise Ltd',
    year: '2020',
    status: 'Completed'
  },
  {
    title: 'BPDB 33/11 KV AIS Substation, Kurigram, Rangpur',
    description: 'Earthing Goods supply, Fabrication, Installation, and Erection.',
    imageSrc: 'https://placehold.co/600x400/f59e0b/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/kurigram-rangpur',
    category: 'Substation',
    client: 'Novelty Infrastructure Limited',
    year: '2020',
    status: 'Completed'
  },
  {
    title: 'BPDB 33/11 KV AIS Substation, Lalmonirha, Rangpur',
    description: 'Earthing Goods supply, Fabrication, Installation, and Erection.',
    imageSrc: 'https://placehold.co/600x400/1e40af/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/lalmonirha-rangpur',
    category: 'Substation',
    client: 'Kalpataru Power Transmission Limited',
    year: '2020',
    status: 'Completed'
  },
  {
    title: 'BPDB 33/11 KV AIS Substation, Kaliganj, Rangpur',
    description: 'Transformer Oil centrifuge and Earthing Goods supply, Fabrication, Installation, and Erection.',
    imageSrc: 'https://placehold.co/600x400/dc2626/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/kaliganj-rangpur',
    category: 'Substation',
    client: 'Optimal Track Automation & Engineering',
    year: '2020',
    status: 'Completed'
  },
  {
    title: 'WZPDCL GIS- 33/11 KV, 2X20/26/66 MVA Substation',
    description: 'Erection, Installation, Fabrication, cable Pulling, complete accessories work, Testing and Commissioning work at Mohessorpara, Khulna and MAN Campus, Kushtia.',
    imageSrc: 'https://placehold.co/600x400/059669/ffffff?text=WZPDCL+Substation',
    imageHint: 'wzpdc substation',
    href: '/projects/completed/wzpdc-substation',
    category: 'Substation',
    client: 'Ideal Electrical Enterprise Ltd',
    year: '2020-2021',
    status: 'Completed'
  },
  {
    title: '33/11 kv substation Control Building Construction',
    description: 'Control Building Construction work at WZPDCL, Kushtia housing.',
    imageSrc: 'https://placehold.co/600x400/7c3aed/ffffff?text=Control+Building',
    imageHint: 'control building',
    href: '/projects/completed/control-building',
    category: 'Civil Construction',
    client: 'KEC International Limited',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'Repair, Maintenance Installation of defective GIS 132/11 KV Substation',
    description: 'Maintenance and repair work at MSML, Chittagong.',
    imageSrc: 'https://placehold.co/600x400/ea580c/ffffff?text=Maintenance+Work',
    imageHint: 'maintenance work',
    href: '/projects/completed/msml-maintenance',
    category: 'Maintenance',
    client: 'Modern Steel Mills Limited',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 KV, 8X 10/14MVA & 16/20 MVA SUBSTATION',
    description: 'Fabrication, Erection & Installation Work, LOT-2.',
    imageSrc: 'https://placehold.co/600x400/f59e0b/ffffff?text=Substation+Work',
    imageHint: 'substation work',
    href: '/projects/completed/breb-substation-lot2',
    category: 'Substation',
    client: 'ERA Construction',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'BREB 33/11 kv substation power cable pulling and power Termination',
    description: 'Power cable pulling and termination work for substation projects.',
    imageSrc: 'https://placehold.co/600x400/1e40af/ffffff?text=Cable+Work',
    imageHint: 'cable work',
    href: '/projects/completed/cable-pulling',
    category: 'Cable Work',
    client: 'Reverie Power & Automation Engineering Ltd',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'PGCB-400 KV Transmission Line, Bogura to Rohanpur-T',
    description: 'High voltage transmission line construction and installation.',
    imageSrc: 'https://placehold.co/600x400/dc2626/ffffff?text=Transmission+Line',
    imageHint: 'transmission line',
    href: '/projects/completed/pgcb-400kv',
    category: 'Transmission Line',
    client: 'Energypac Engineering Limited',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'PGCB-230 KV Double Circuit Transmission Line, Bogura to Rohanpur',
    description: 'Double circuit transmission line construction and installation.',
    imageSrc: 'https://placehold.co/600x400/059669/ffffff?text=Transmission+Line',
    imageHint: 'transmission line',
    href: '/projects/completed/pgcb-230kv',
    category: 'Transmission Line',
    client: 'Solarland Bangladesh Co. Ltd.',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'Tower Erection on 400 kv madunaghat - matarbari D/C TL',
    description: 'Tower erection work under contract no PGCB/MUSCCFPP/packeg-02/TL-2.',
    imageSrc: 'https://placehold.co/600x400/7c3aed/ffffff?text=Tower+Erection',
    imageHint: 'tower erection',
    href: '/projects/completed/tower-erection',
    category: 'Transmission Line',
    client: 'HS Engineering and Tecnologi',
    year: '2021',
    status: 'Completed'
  },
  {
    title: 'Recovery and installation of 33 kv and 11 kv Distribution line',
    description: 'From Shahid A.H.M Kamruzzaman Airport to Nawhata Bridge 20 km circuit -Division-03. NESCO Ltd. Rajshahi.',
    imageSrc: 'https://placehold.co/600x400/ea580c/ffffff?text=Distribution+Line',
    imageHint: 'distribution line',
    href: '/projects/completed/nesco-distribution',
    category: 'Distribution Line',
    client: 'China National Technical Import and Export Corporation',
    year: '2022',
    status: 'Completed'
  },
  {
    title: 'Hot dip Galvanize Steel Structure Gantry Tower, Central Grid SS',
    description: 'CT, PT, CB Structure Supply, fabrication, Installation at PGCB, Daulatpur, Khulna.',
    imageSrc: 'https://placehold.co/600x400/f59e0b/ffffff?text=Steel+Structure',
    imageHint: 'steel structure',
    href: '/projects/completed/central-grid-ss',
    category: 'Steel Structure',
    client: 'PGCB',
    year: '2022',
    status: 'Completed'
  },
  {
    title: 'Hot dip Galvanize Steel Structure Gantry Tower, WZPDCL',
    description: 'CT, PT, CB Structure, Cable Tray, Connector Supply, fabrication, Installation at Mohessorpara, Khulna and MAN Campus, Kushtia.',
    imageSrc: 'https://placehold.co/600x400/1e40af/ffffff?text=Steel+Structure',
    imageHint: 'steel structure',
    href: '/projects/completed/wzpdc-steel',
    category: 'Steel Structure',
    client: 'WZPDCL',
    year: '2022',
    status: 'Completed'
  },
  {
    title: 'Hot dip Galvanize Steel Structure Gantry Tower, BREB Sherpur',
    description: 'CT, PT, CB Structure, Cable Tray, Connector Supply, fabrication, Installation at -33 kv Bay Extension Project.',
    imageSrc: 'https://placehold.co/600x400/dc2626/ffffff?text=Steel+Structure',
    imageHint: 'steel structure',
    href: '/projects/completed/breb-sherpur-steel',
    category: 'Steel Structure',
    client: 'BREB',
    year: '2022',
    status: 'Completed'
  },
  {
    title: 'SIRAJGANJ 7.6 MW GRID CONNECTED SOLAR PHOTOVOLTAIC POWER PLANT',
    description: 'Full wiring, MDB, SDB, Earthing material supply installation testing and commissioning.',
    imageSrc: 'https://placehold.co/600x400/059669/ffffff?text=Solar+Power+Plant',
    imageHint: 'solar power plant',
    href: '/projects/completed/sirajganj-solar',
    category: 'Solar Plant',
    client: 'Solarland Bangladesh Co. Ltd.',
    year: '2022',
    status: 'Completed'
  },
];

export const products = [
  {
    title: 'Switchgear',
    description: 'Reliable and safe switchgear for various voltage levels, designed for optimal performance and protection in electrical distribution systems.',
    longDescription: 'Our switchgear solutions are engineered to provide maximum safety and reliability for electrical power distribution systems. Designed to meet international standards, our switchgear products offer superior protection against electrical faults, ensuring continuous operation of your electrical systems. With compact designs and modular construction, our switchgear can be customized to meet specific project requirements while maintaining ease of installation and maintenance.',
    imageSrc: 'https://images.unsplash.com/photo-1620283085439-39aed3b5e4b6?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'electrical switchgear',
    href: '/products/switchgear',
    specifications: {
      'Voltage Rating': '11kV - 33kV',
      'Current Rating': '630A - 2500A',
      'Frequency': '50/60 Hz',
      'Protection Class': 'IP54',
      'Standards': 'IEC 62271-200',
      'Dimensions': 'Customizable',
      'Installation': 'Indoor/Outdoor',
      'Warranty': '2 Years',
    },
    features: [
      'High operational reliability',
      'Compact design',
      'Low maintenance requirements',
      'Extended service life',
      'Environmental friendliness',
      'Easy installation and commissioning',
      'Customizable configurations',
      'Advanced safety features',
    ],
    applications: [
      'Power plants',
      'Substations',
      'Industrial facilities',
      'Commercial buildings',
      'Infrastructure projects',
    ],
  },
  {
    title: 'Busbar Trunking System',
    description: 'Flexible and efficient power distribution solutions for commercial and industrial applications, offering space-saving and reliable electrical distribution.',
    longDescription: 'Our Busbar Trunking Systems provide a modern alternative to traditional cable-based power distribution. These systems offer significant advantages in terms of space utilization, flexibility, and maintenance. With high short-circuit ratings and excellent thermal performance, our busbar systems ensure reliable power distribution in various environments. The modular design allows for easy expansion and reconfiguration, making it ideal for evolving electrical requirements in commercial and industrial settings.',
    imageSrc: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'busbar system',
    href: '/products/busbar-trunking-system',
    specifications: {
      'Current Rating': '100A - 6300A',
      'Voltage': '415V - 1000V',
      'Frequency': '50/60 Hz',
      'Protection Class': 'IP55',
      'Short Circuit Rating': 'Up to 100kA',
      'Conductor Material': 'Copper/Aluminum',
      'Installation': 'Indoor',
      'Compliance': 'IEC 61439-6',
    },
    features: [
      'Space-saving design',
      'Flexible configuration',
      'Easy installation and maintenance',
      'High short-circuit withstand',
      'Low voltage drop',
      'Reduced power losses',
      'Fire resistant',
      'Tap-off points for convenient power access',
    ],
    applications: [
      'Commercial buildings',
      'Data centers',
      'Manufacturing facilities',
      'Shopping malls',
      'Hospitals',
    ],
  },
  {
    title: 'Transformer',
    description: 'High-quality transformers for power transmission and distribution, engineered for efficiency and reliability in various applications.',
    longDescription: 'Our transformer range includes distribution transformers, power transformers, and special-purpose transformers designed for specific applications. Built with high-quality materials and advanced manufacturing techniques, our transformers offer excellent efficiency, low losses, and long service life. Each transformer undergoes rigorous testing to ensure compliance with international standards and specifications. We provide both oil-filled and dry-type transformers to suit different environmental and safety requirements.',
    imageSrc: 'https://images.unsplash.com/photo-1626193082855-c3224f769638?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'power transformer',
    href: '/products/transformer',
    specifications: {
      'Power Rating': '100kVA - 50MVA',
      'Primary Voltage': 'Up to 132kV',
      'Secondary Voltage': 'As per requirement',
      'Frequency': '50/60 Hz',
      'Cooling': 'ONAN/ONAF/OFAF',
      'Vector Group': 'Dyn11, YNd11, etc.',
      'Impedance': 'As per standard',
      'Insulation Class': 'A/F/H',
    },
    features: [
      'High efficiency',
      'Low losses',
      'Reduced noise level',
      'Temperature monitoring',
      'Overload capability',
      'Compact footprint',
      'Long service life',
      'Low maintenance',
    ],
    applications: [
      'Power generation plants',
      'Transmission substations',
      'Distribution networks',
      'Industrial facilities',
      'Renewable energy projects',
    ],
  },
  {
    title: 'Lightning Protection',
    description: 'Advanced systems to protect structures from lightning strikes, safeguarding buildings, equipment, and personnel from lightning-related damages.',
    longDescription: 'Our Lightning Protection Systems provide comprehensive protection against direct lightning strikes and the secondary effects of lightning. Designed in accordance with international standards, our systems include air terminals, down conductors, earth termination systems, and surge protection devices. We offer both conventional and early streamer emission (ESE) lightning protection systems to suit different structures and risk levels. Our solutions are customized based on risk assessment and structural characteristics to provide optimal protection.',
    imageSrc: 'https://images.unsplash.com/photo-1605003179269-c446bb939f00?q=80&w=2071&auto=format&fit=crop',
    imageHint: 'lightning rod',
    href: '/products/lightning-protection',
    specifications: {
      'Protection Level': 'I, II, III, IV as per IEC 62305',
      'Material': 'Copper, Aluminum, Stainless Steel',
      'Down Conductor': '50mm² - 95mm²',
      'Earth Resistance': '< 10 Ohms',
      'Air Terminal Height': 'As per protection radius',
      'Standards': 'IEC 62305, NFPA 780',
      'Installation': 'External/Internal',
      'Maintenance': 'Annual inspection recommended',
    },
    features: [
      'Complete protection system',
      'Customized design',
      'Aesthetic integration with structures',
      'Corrosion-resistant materials',
      'Surge protection capability',
      'Easy maintenance',
      'Long service life',
      'Compliance with international standards',
    ],
    applications: [
      'High-rise buildings',
      'Industrial facilities',
      'Telecommunication towers',
      'Historical monuments',
      'Residential complexes',
    ],
  },
  {
    title: 'Cable Management',
    description: 'Comprehensive solutions for organizing and protecting cables, ensuring efficient cable routing, identification, and maintenance in various environments.',
    longDescription: 'Our Cable Management Systems provide organized and protected pathways for power and data cables in various environments. Our product range includes cable trays, ladders, trunking, conduits, and accessories designed to support, protect, and organize cables throughout their routes. Made from high-quality materials with various finishes, our cable management solutions offer excellent corrosion resistance and load-bearing capacity. The systems are designed for easy installation, maintenance, and future expansion, ensuring long-term reliability of cable infrastructure.',
    imageSrc: 'https://images.unsplash.com/photo-1601996759374-7d2dca2596f8?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'cable management',
    href: '/products/cable-management',
    specifications: {
      'Material': 'Galvanized Steel, Stainless Steel, Aluminum',
      'Load Capacity': 'Up to 100kg/m',
      'Width Range': '50mm - 600mm',
      'Height Range': '50mm - 100mm',
      'Finish': 'Pre-galvanized, Hot-dip galvanized, Powder coated',
      'Standards': 'IEC 61537, NEMA VE 1',
      'Fire Rating': 'Available as per requirement',
      'Accessories': 'Comprehensive range available',
    },
    features: [
      'Versatile design',
      'High load-bearing capacity',
      'Corrosion resistance',
      'Easy installation',
      'Comprehensive accessory range',
      'Adaptable to various environments',
      'Space-efficient solutions',
      'Maintenance-friendly',
    ],
    applications: [
      'Commercial buildings',
      'Data centers',
      'Industrial facilities',
      'Infrastructure projects',
      'Power plants',
    ],
  },
  {
    title: 'IPS & UPS',
    description: 'Uninterruptible and instant power supply systems providing reliable backup power for critical applications, ensuring continuous operation during power outages.',
    longDescription: 'Our Uninterruptible Power Supply (UPS) and Instant Power Supply (IPS) systems provide reliable backup power for critical applications. These systems ensure continuous operation during power outages, protecting sensitive equipment from power disturbances. Our range includes online double-conversion UPS, line-interactive UPS, and standby UPS systems with various power ratings to suit different applications. With advanced monitoring capabilities and high efficiency, our power backup solutions offer peace of mind for businesses and organizations that cannot afford downtime.',
    imageSrc: 'https://images.unsplash.com/photo-1620283085439-39aed3b5e4b6?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'uninterruptible power supply',
    href: '/products/ips-ups',
    specifications: {
      'Power Rating': '1kVA - 500kVA',
      'Input Voltage': '220V/380V/400V',
      'Output Voltage': '220V/380V/400V',
      'Frequency': '50/60 Hz',
      'Topology': 'Online Double Conversion, Line Interactive, Standby',
      'Backup Time': 'Customizable',
      'Efficiency': 'Up to 96%',
      'Communication': 'SNMP, RS232, USB',
    },
    features: [
      'High reliability',
      'Pure sine wave output',
      'Advanced battery management',
      'Intelligent monitoring',
      'Overload protection',
      'Scalable solutions',
      'Low noise operation',
      'Remote management capability',
    ],
    applications: [
      'Data centers',
      'Healthcare facilities',
      'Industrial control systems',
      'Telecommunications',
      'Financial institutions',
    ],
  },
];
